uptake jersey 2.18 to bring in hk2 2.4.0-b12 instead of 2.4.0-b06 due to java.lang.NoSuchMethodError: org.glassfish.hk2.utilities.ClasspathDescriptorFileFinder.<init>(Ljava/lang/ClassLoader;[Ljava/lang/String;)V